reorder_imports = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
wrap_comments = true
format_strings = true
imports_granularity = "Crate"
use_field_init_shorthand = true
newline_style = "Unix"
unstable_features = true
comment_width = 100
normalize_comments = true
