[registries.crates.io]
protocol = "sparse"

# [unstable]
# codegen-backend = true

# [profile.dev]
# codegen-backend = "cranelift"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = [
    "-Zshare-generics=off", # (Nightly)
    "-Zthreads=8", # (Nightly) Use improved multithreading with the recommended amount of threads.
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=/usr/bin/mold", # Use mold linker: mold is up to 5× (five times!) faster than LLD.
    "-Zcodegen-backend=cranelift", # (Nightly) Use Cranelift codegen backend.
    "-Zshare-generics=y", # (Nightly) Make the current crate share its generic instantiations.
    "-Zthreads=8", # (Nightly) Use improved multithreading with the recommended amount of threads.
]
